language: python
dist: trusty

python:
  - "2.7"

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libqt4-core
      - libqt4-gui
      - python-qt4

matrix:
  fast_finish: true
  exclude:
    - os: osx
  include:
    - os: osx
      language: generic
      python: "2.7"

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew install pyqt;
        export PYTHONPATH=$PYTHONPATH:/usr/local/Cellar/pyqt/;
        prefix=`python-config --prefix`;
        pypath=$prefix/lib/libpython$TRAVIS_PYTHON_VERSION.dylib;
        pylib="-DPYTHON_LIBRARY=$pypath";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        ln -s /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/PyQt4
              $VIRTUAL_ENV/lib/python2.7/site-packages;
        ln -s /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/sip*
              $VIRTUAL_ENV/lib/python2.7/site-packages;
    fi
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python setup.py develop

script:
  - python setup.py test