language: python
dist: trusty

python:
  - "2.7"

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libqt4-core
      - libqt4-gui
      - python-qt4

matrix:
  fast_finish: true
  exclude:
    - os: osx
  include:
    - os: osx
      language: generic
      python: "2.7"

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then
        prefix=`python-config --prefix`;
        pypath=$prefix/lib/libpython$TRAVIS_PYTHON_VERSION.dylib;
        pylib="-DPYTHON_LIBRARY=$pypath";
    fi
  - pip install --upgrade pip

before_script:
  - pip install -r requirements.txt
  - pip install -e .
  - cp -r /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/PyQt4 usr/lib/python$TRAVIS_PYTHON_VERSION/site-packages/
  - echo $PYTHONPATH

script: python setup.py test
