language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libqt4-core
      - libqt4-gui
      - python-pyqt4

matrix:
  fast_finish: true
  exclude:
    - os: osx
  include:
    - os: osx
      language: generic
      python: "2.7"

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then
        prefix=`python-config --prefix`;
        pypath=$prefix/lib/libpython$python.dylib;
        pylib="-DPYTHON_LIBRARY=$pypath";
    fi
  - pip install --upgrade pip

before_script:
  - pip install -r requirements.txt
  - python setup.py install

script: python setup.py test