language: python
dist: trusty

python:
  - "2.7"

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libqt4-core
      - libqt4-gui
      - python-qt4

matrix:
  fast_finish: true
  exclude:
    - os: osx
  include:
    - os: osx
      language: generic
      python: "2.7"

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then
        prefix=`python-config --prefix`;
        pypath=$prefix/lib/libpython$python.dylib;
        pylib="-DPYTHON_LIBRARY=$pypath";
    fi
  - pip install --upgrade pip
  - export PATH=/usr/bin:$PATH

before_script:
  - pip install -r requirements.txt
  - python setup.py build

script: python setup.py test